[project]
name = "slm-based"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub[hf-xet]>=0.36.0",
    "marker-pdf[full]>=1.10.1",
    "rank-bm25>=0.2.2",
    "sentence-transformers>=3.0.0",
]
